package me.sdevil507.drools.rules

/*
 * 关键字activation_group设置异或组,有一个条件成功其他的将不再执行
 * 可以配合salience属性设置规则执行优先级,salience越高越先执行
 */

rule "rule1"
    agenda-group "ag"
    // 设置互斥组
    activation-group "ag"
    when
    then
        System.out.println("互斥条件1");
end

rule "rule2"
    agenda-group "ag"
    // 此处未设置互斥,所以会被执行
    when
    then
        System.out.println("互斥条件2");
end

rule "rule2.5"
    agenda-group "ag"
    // enable属性设置规则是否启用
    enabled true
    when
    then
        System.out.println("规则2.5!!!");
end

rule "rule3"
    agenda-group "ag"
    // 设置互斥组
    activation-group "ag"
    // 该规则先执行
    salience 99
    when
    then
        System.out.println("互斥条件3");
end